spring:
  application:
    name: 'Pacotes de Viagens'

  datasource:
    url: jdbc:postgresql://localhost:5432/pacotes-viagens-db
    username: postgres
    password: postgres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_class: thread
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation:true

server:
  error:
    include-message: always
  port: 8081